#pragma once

sf::String TileMap2[height] = {
	"                         ",
	"                         ",
	"                         ",
	"                         ",
	"                         ",
	"      w           w      ",
	"      w           w      ",
	"      w           w      ",
	"      wwwww   wwwww      ",
	"      w           w      ",
	"      w           w      ",
	"      w           w      ",
	"      w     w     w      ",
	"      w     w     w      ",
	"      w           w      ",
	"      w           w      ",
	"      w           w      ",
	"      wwwww   wwwww      ",
	"      w           w      ",
	"      w           w      ",
	"      w           w      ",
	"                         ",
	"                         ",
	"                         ",
	"                         ",
};