#pragma once

sf::String TileMap3[height] = {
	"                         ",
	"                         ",
	"   w     w     w     w   ",
	"                         ",
	"     w             w     ",
	"                         ",
	"       w         w       ",
	"                         ",
	"         w     w         ",
	"            w            ",
	"   w                 w   ",
	"   w                 w   ",
	"   w                 w   ",
	"   w                 w   ",
	"   w                 w   ",
	"            w            ",
	"         w     w         ",
	"                         ",
	"       w         w       ",
	"                         ",
	"     w             w     ",
	"                         ",
	"   w     w     w     w   ",
	"                         ",
	"                         ",
};