#pragma once

sf::String TileMap4[height] = {
	"                         ",
	"   w   w         w   w   ",
	"                         ",
	"   w   w         w   w   ",
	"                         ",
	"   w        w        w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w                 w   ",
	"                         ",
	"   w        w        w   ",
	"                         ",
	"   w   w         w   w   ",
	"                         ",
	"   w   w         w   w   ",
	"                         ",
};
