#pragma once

sf::String TileMap5[height] = {
	"                         ",
	"    w                    ",
	"     w                   ",
	"      w                  ",
	"       w                 ",
	"        w       wwwwww   ",
	"  w      w               ",
	"   w      w              ",
	"    w                    ",
	"     w                   ",
	"      w                  ",
	"       w                 ",
	"        w      w         ",
	"                w        ",
	"                 w       ",
	"                  w      ",
	"                   w     ",
	"             w      w    ",
	"              w      w   ",
	"   wwwwww      w      w  ",
	"                w        ",
    "                 w       ",
	"                  w      ",
	"                   w     ",
	"                         ",
};
