#pragma once

sf::String TileMap6[height] = {
	"                         ",
    "       wwwwwwwwwww       ",
	"            w            ",
	"            w            ",
	"            w            ",
	"            w            ",
	"            w            ",
	"   w        w        w   ",
	"   w        w        w   ",
	"   w   ww   w   ww   w   ",
	"   w        w        w   ",
	"   w        w        w   ",
	"   wwwwwwwwwwwwwwwwwww   ",
	"   w        w        w   ",
	"   w        w        w   ",
	"   w   ww   w   ww   w   ",
	"   w        w        w   ",
	"   w        w        w   ",
	"            w            ",
	"            w            ",
	"            w            ",
	"            w            ",
	"            w            ",
	"       wwwwwwwwwww       ",
	"                         ",
};
